### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'log'

### ISSUE THREAD

**Issue by shenweiyan** [yodeng/fsplit#2]
It seems like specifying the log parameter is necessary. How should this parameter be specified?
```
$ /SoftWare/Python-3.7.3/bin/fsplit split -i Undetermined_R1.fq.gz -I Undetermined_R2.fq.gz -b barcode.txt -m 1 -o ./
Traceback (most recent call last):
  File "/SoftWare/Python-3.7.3/bin/fsplit", line 8, in <module>
    sys.exit(main())
  File "/SoftWare/Python-3.7.3/lib/python3.7/site-packages/fsplit/utils.py", line 209, in wrapper
    value = func(*args, **kwargs)
  File "/SoftWare/Python-3.7.3/lib/python3.7/site-packages/fsplit/main.py", line 11, in main
    logs = log(logfile=args.log)
AttributeError: 'Namespace' object has no attribute 'log'

$ /SoftWare/Python-3.7.3/bin/fsplit split -i Undetermined_R1.fq.gz -I Undetermined_R2.fq.gz -b barcode.txt -m 1 -o ./ --log=log.txt
usage: fsplit [-h] [-v] command ...
fsplit: error: unrecognized arguments: --log=log.txt
```

**Comment by yodeng** [comment]
oh, I'm sorry,  the "--log" & "--debug" parameters were not parsed in "split" subcommand, and I've already fixed it https://github.com/yodeng/fsplit/commit/d06f173931529df82a7d4c54d44d46c9bcfc3930. Thanks for your nice issue!

**Comment by yodeng** [comment]
Oh, I'm sorry, the "--log" & "--debug" parameters were not parsed in "split" subcommand, and I'v already fixed it https://github.com/yodeng/fsplit/commit/d06f173931529df82a7d4c54d44d46c9bcfc3930. Thanks for you nice issue. @shenweiyan

**Comment by yodeng** [comment]
Oh, I'm sorry, the "--log" & "--debug" parameters were not parsed in "split" subcommand, and I'v already fixed it https://github.com/yodeng/fsplit/commit/d06f173931529df82a7d4c54d44d46c9bcfc3930. Thanks for your nice issue. @shenweiyan
